# Generated by Django 4.2.3 on 2023-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0003_rename_hobbit_habbit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habbit',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='DAILY'),
        ),
    ]
